### PR TITLE
Resolve BC with composer 1.0.0-alpha4

### PR DESCRIPTION
**Pull request by b-durand**
Warning, the default stability switch to stable (more details on
https://groups.google.com/forum/#!topic/composer-dev/_g3ASeIFlrc/discussion).

### CODE REVIEW

**Comment by b-durand** [comment]
Don't change beta stability with RC at this time, because composer has a bug with components that have at least one required dependence (see composer/composer#985).

**Comment by b-durand** [comment]
"It's not a bug, it's a feature." :smiley:

**Comment by Maks3w** [comment]
@b-durand Please rebase your PR seems to be something wrong in the git history

**Comment by Maks3w** [comment]
@ralphschindler @weierophinney Have sense the behavior of composer. I think that we can go ahead with this after @b-durand fix the PR history

**Comment by b-durand** [comment]
@Maks3w I have rebase (wrong master... a little strange if ralph don't force the history)

**Pull request merged**
