### PR TITLE
remove ZF2 wiki link. It is dead.

### PR DESCRIPTION
**Pull request by sasezaki**
and currently ZF developers no longer use any wiki system ..

### CODE REVIEW

**Comment by samsonasik** [comment]
:+1:

**Comment by weierophinney** [comment]
This actually needs to be done against `build/zf2/index.template.html`, please, as that's used to generate this page.

**Comment by weierophinney** [comment]
I've incorporated the change into `build/zf2/index.template.html`, and the change will propagate the next time the composer repository is updated.

**Comment by sasezaki** [comment]
oh, I didn't notice about `build/zf2/index.template.html`, sorry. thanks!

**Pull request closed without merging**
