### PR TITLE
Fix composer package list

### PR DESCRIPTION
**Pull request by Maks3w**

### CODE REVIEW

**Comment by weierophinney** [comment]
I'm going to wait on this until after @ralphschindler is done with moving the service components into separate repos.

**Comment by Maks3w** [comment]
:o but that packages already exists in packages.zendframework.com with the fixed names

**Comment by weierophinney** [comment]
@Maks3w true, but we won't be updating packages.zendframework.com, and thus packages.json, until that migration is done.

**Comment by Maks3w** [comment]
This only fix the list in the webpage, all the rest is ok.

**Pull request closed without merging**
